# name: Run Tests

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'
#           # Tự động cache pip để các lần chạy sau nhanh hơn
#           cache: 'pip' 

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           # Lệnh này sẽ tìm và xóa dòng pywin32 trong file requirements.txt
#           # Chúng ta dùng 'sed' để xử lý file trước khi pip install chạy
#           sed -i '/pywin32/d' saleappv1/requirements.txt
          
#           # Sau đó mới tiến hành cài đặt
#           pip install -r saleappv1/requirements.txt
#       - name: Run tests with pytest
#         run: |
#           # 1. Định vị vị trí hiện tại để debug (xem trong log)
#           pwd
          
#           # 2. Thêm tất cả thư mục vào PYTHONPATH để tránh lỗi Import
#           export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/saleappv1
          
#           # 3. Chạy pytest mà KHÔNG chỉ định file cụ thể
#           # Pytest sẽ tự tìm các file có tên test_*.py trong toàn bộ project
#           pytest